---
apiVersion: v1
kind: Service
metadata:
  name: kube-scheduler-extender
  labels:
    app: kube-scheduler-extender
  namespace: kube-system
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    app: kube-scheduler-extender

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-scheduler-extender
  labels:
    app: kube-scheduler-extender
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-scheduler-extender
  template:
    metadata:
      labels:
        app: kube-scheduler-extender
    spec:
      containers:
      - name: kube-scheduler-extender
        image: registry.cn-hangzhou.aliyuncs.com/generals-kuber/kube-scheduler-extender:01-simple-v0.0.7
        imagePullPolicy: IfNotPresent
        command: ["/kube-scheduler-extender"]

